FROM nginx:1.23.2

RUN apt update && apt install -y nano less fail2ban iptables

RUN rm -rf /etc/fail2ban/jail.d/defaults-debian.conf

RUN unlink /var/log/nginx/access.log
RUN unlink /var/log/nginx/error.log