FROM nginx:1.25.2

RUN apt update && apt install -y nano less fail2ban iptables

RUN unlink /var/log/nginx/access.log
RUN unlink /var/log/nginx/error.log

RUN rm -rf /etc/fail2ban/jail.d/defaults-debian.conf

COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY fail2ban/jail.d/nginx-limit-req.conf /etc/fail2ban/jail.d/nginx-limit-req.conf